# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         xchar
version:      0.1
version_from: version
installdirs:  site
requires:
    Tk:                            8
    X11::Protocol:                 0.55

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
